### ISSUE TITLE
throws return require('open')(url, options)  - when selecting a dev tool plugin

### ISSUE THREAD

**Issue by ddennis** [expo/dev-plugins#24]
I have just updated to expo 50 and want to try out the dev-plugins.
My app is running in expo go

I am using windows and have the added the following. Have also checked **npm expo --fix** 

    "@dev-plugins/react-navigation": "^0.0.5",
    "expo": "~50.0.6",

This error is thrown as soon as i select **Open devtools plugin - @dev-plugins/react-navigation**   
I have also tried using **@dev-plugins/react-query** it gives the same error

    return require('open')(url, options);
    ^
    TypeError: require(...) is not a function
    at startBrowserProcess (C:\.......\node_modules\better-opn\dist\index.js:106:25)
    at Object.module.exports [as default] (C:\Users\...\node_modules\better-opn\dist\index.js:122:14)
    at Object.openBrowserAsync (C:\Users\.......\node_modules\@expo\cli\src\utils\open.ts:20:40)
    at Object.action (C:\Users\.......\node_modules\@expo\cli\src\start\interface\interactiveActions.ts:170:49)
    at DevServerManagerActions.openMoreToolsAsync                 (C:\Users\.......\node_modules\@expo\cli\src\start\interface\interactiveActions.ts:177:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at ReadStream.KeyPressHandler.handleKeypress (C:\Users\.......\node_modules\@expo\cli\src\start\interface\KeyPressHandler.ts:43:7)

Any help would much appreciated

**Comment by Kudo** [comment]
that's strange! could you share your nodejs version? does the problem happen only on the project or also on new `npx create-expo-app` project?

**Comment by Kudo** [comment]
i'm closing this issue and happy to follow up if this problem is still reproducible.
